### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by torounit**
prefer-stable is true.

### CODE REVIEW

**Comment by KorvinSzanto** [comment]
Does this work? What does it do differently? I was having trouble with stability settings because of the dev dependencies in concrete5.

**Comment by olsgreen** [comment]
This should only be set to stable on release, it will tell composer to use
the lastest stable version of the core, instead of the master development
branch.

**Comment by olsgreen** [comment]
@torounit We'll do this before we hit 1.0, for the moment I'm gonna close this.

**Comment by KorvinSzanto** [comment]
@olsgreen I'm not sure that we're going to be versioning like this. I think we may stick with no releases and just have a stable development branch. I would prefer having the latest release pulled instead of having the current dev pulled, so if that's all this does I'd argue we should include it today. There's no reason we need to be on dev of concrete5 that I can see at this point.

**Comment by KorvinSzanto** [comment]
As @olsgreen says we will be doing this, however versioning is up for debate. I've begun some work to eliminate @dev requirements from concrete5/concrete5, hopefully with that and #4 we will be completely stable.

**Review by KorvinSzanto — APPROVED** [review]
This needs to be added.

**Pull request merged**
