### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by danielgasser**
Added the way on how to install in a Windows environment

### CODE REVIEW

**Review by mlocati — COMMENTED** [review]
IMHO it's enough to say something like

   On Windows use `\` instead of `/`.

**Comment by danielgasser** [comment]
Yes, but the dot must be removed too and (don't know if that's only me) it doesn't work if one is not in the `\vendor\bin\` when launching `concrete5 c5:install -i`

**Comment by mlocati** [comment]
If you open a comma d prompt, enter the concrete5 root directory and type this command;
```bat
.\vendor\bin\concrete5 c5:install -i
```
What's he error that you have?

**Comment by danielgasser** [comment]
None, you're right... So I think just mentioning that on Windows it's a back-slash instead of a slash isn't really necessary, what do you think? Then this PR is obsolete IMO.

**Pull request closed without merging**
